# version: '3.8'

services:
  kafka:
    image: bitnami/kafka:3.4
    ports: ["9092:9092"]
    environment:
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092

  elasticsearch:
    image: elasticsearch:8.8.0
    environment:
      - discovery.type=single-node
    ports: ["9200:9200"]
