name: Security Scans

on:
  schedule:
    - cron: '0 0 * * 1' # Weekly on Monday
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run Bandit security scan
      run: |
        pip install bandit
        bandit -r core/ -f json -o bandit_results.json
    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: bandit-results
        path: bandit_results.json

  trivy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: docker build -t shieldnet .
    - name: Scan image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'shieldnet'
        format: 'table'
        severity: 'CRITICAL,HIGH'
        exit-code: '1'
        ignore-unfixed: true

  dependabot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check dependencies
      run: |
        pip install safety
        safety check --full-report
